<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Computer" failures="0" tests="12" name="Aston_Unit.Lesson_14_testng.FactorialTest" time="0.048" errors="1" timestamp="30 Nov 2024 15:40:45 GMT">
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositiveSmallNumbers" time="0.001"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositive" time="0.001"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositive" time="0.001"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositiveSmallNumbers" time="0.002"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialOverflow" time="0.004">
    <error message="&#039;java.lang.Throwable org.testng.Assert.expectThrows(java.lang.Class, org.testng.Assert$ThrowingRunnable)&#039;" type="java.lang.NoSuchMethodError">
      <![CDATA[java.lang.NoSuchMethodError: 'java.lang.Throwable org.testng.Assert.expectThrows(java.lang.Class, org.testng.Assert$ThrowingRunnable)'
	at Aston_Unit.Lesson_14_testng.FactorialTest.testFactorialOverflow(FactorialTest.java:20)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testFactorialOverflow -->
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositive" time="0.001"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialNegativeNumber" time="0.025"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositive" time="0.001"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositiveSmallNumbers" time="0.000"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositive" time="0.001"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositive" time="0.010"/>
  <testcase classname="Aston_Unit.Lesson_14_testng.FactorialTest" name="testFactorialPositive" time="0.001"/>
</testsuite> <!-- Aston_Unit.Lesson_14_testng.FactorialTest -->
